Controllers/Admin/AdminController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="AdminController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// <summary>
//   Defines the AdminController.cs type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SecureNetworks.DataBaseContext;
using SecureNetworks.Helpers;
using SecureNetworks.Models.DBModels;

namespace SecureNetworks.Controllers.Admin
{
    public class AdminController : Controller
    {
        private readonly SecureNetworkDBContext _secureNetworkDbContext;

        private readonly IWebHostEnvironment _webHostEnvironment;

        public AdminController(SecureNetworkDBContext secureNetworkDbContext, IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            _secureNetworkDbContext = secureNetworkDbContext;
        }

        [HttpGet]
        public IActionResult Index(int page = 1, int pageSize = 10)
        {
            var products = _secureNetworkDbContext.tbl_SNProducts.OrderBy(p => p.SNProductId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            var totalProducts = _secureNetworkDbContext.tbl_SNProducts.Count();

            var model = new PaginationHelper<SNProductsEntity>(products, totalProducts, page, pageSize);

            return View(model);
        }

        // Action method to display form for adding a new product
        [HttpGet]
        public IActionResult Create()
        {
            TempData["AddSuccess"] = null;
            TempData["AddError"] = null;
            TempData["UpdateSuccess"] = null;
            TempData["UpdateError"] = null;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SNProductsEntity snProductsEntity, IFormFile? productImage)
        {
            TempData["AddSuccess"] = null;
            TempData["AddError"] = null;

            if (ModelState.IsValid)
            {
                try
                {
                    // Check if a file is uploaded
                    if (productImage is { Length: > 0 })
                    {
                        // Generate a unique filename for the image
                        var uniqueFileName = Guid.NewGuid() + "_" + Path.GetFileName(productImage.FileName);

                        // Get the path of the wwwroot/img folder where images will be stored
                        var uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");

                        // Combine the unique filename with the path to store the image
                        var filePath = Path.Combine(uploadsFolder, uniqueFileName);

                        // Copy the uploaded file to the specified path
                        await using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await productImage.CopyToAsync(stream);
                        }

                        // Update the ImageUrl property of the product with the new filename
                        snProductsEntity.SNProductImageUrl = uniqueFileName;
                    }

                    // Set CreateDateTime and ModifieDateTime
                    snProductsEntity.CreateDateTime = DateTime.Now;
                    snProductsEntity.ModifieDateTime = DateTime.Now;

                    // Add the product to the database
                    _secureNetworkDbContext.tbl_SNProducts.Add(snProductsEntity);
                    await _secureNetworkDbContext.SaveChangesAsync();

                    TempData["AddSuccess"] = $"ProductID {snProductsEntity.SNProductId} has been added successfully.";

                    // Redirect to the product list page after successful creation
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // Log or handle the exception appropriately
                    TempData["AddError"] = $"Exception while adding the new product : {ex.Message}";
                }
            }

            // If the model state is not valid, return the view with the model data and errors
            return View(snProductsEntity);
        }

        
        public IActionResult Edit(int id)
        {
            TempData["AddSuccess"] = null;
            TempData["AddError"] = null;
            TempData["UpdateSuccess"] = null;
            TempData["UpdateError"] = null;
            var product = _secureNetworkDbContext.tbl_SNProducts.Find(id);
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, SNProductsEntity snProductsEntity, IFormFile? newImage)
        {
            TempData["UpdateSuccess"] = null;
            TempData["UpdateError"] = null;

            if (id != snProductsEntity.SNProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingProduct = await _secureNetworkDbContext.tbl_SNProducts.FindAsync(id);

                    if (existingProduct == null)
                    {
                        return NotFound();
                    }

                    if (newImage != null)
                    {
                        if (existingProduct.SNProductImageUrl != null)
                        {
                            var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Images", existingProduct.SNProductImageUrl);
                            if (System.IO.File.Exists(imagePath))
                            {
                                System.IO.File.Delete(imagePath);
                            }
                        }

                        
                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + newImage.FileName;

                        
                        var newImagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Images", uniqueFileName);
                        await using (var stream = new FileStream(newImagePath, FileMode.Create))
                        {
                            await newImage.CopyToAsync(stream);
                        }

                        
                        existingProduct.SNProductImageUrl = uniqueFileName;
                    }

                    
                    existingProduct.SNProductName = snProductsEntity.SNProductName;
                    existingProduct.SNProductPrice = snProductsEntity.SNProductPrice;
                    existingProduct.SNProductDescription = snProductsEntity.SNProductDescription;
                    existingProduct.SNProductStock = snProductsEntity.SNProductStock;
                    existingProduct.SNProductRating = snProductsEntity.SNProductRating;
                    existingProduct.SNProductCategory = snProductsEntity.SNProductCategory;
                    existingProduct.ModifieDateTime = DateTime.Now;

                    _secureNetworkDbContext.Update(existingProduct);
                    await _secureNetworkDbContext.SaveChangesAsync();
                    TempData["UpdateSuccess"] = $"ProductID {snProductsEntity.SNProductId} has been updated successfully.";
                }
                catch (Exception ex)
                {
                    TempData["UpdateError"] = $"Exception updating the product : {ex.Message}.";
                }
            }
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            TempData["AddSuccess"] = null;
            TempData["AddError"] = null;
            TempData["UpdateSuccess"] = null;
            TempData["UpdateError"] = null;

            var product = _secureNetworkDbContext.tbl_SNProducts.Find(id);
            if (product != null)
            {
                
                string? filename = product.SNProductImageUrl; 

                
                _secureNetworkDbContext.tbl_SNProducts.Remove(product);
                _secureNetworkDbContext.SaveChanges();

                
                if (filename != null)
                {
                    string imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images", filename);
                    if (System.IO.File.Exists(imagePath))
                    {
                        try
                        {
                            System.IO.File.Delete(imagePath);
                        }
                        catch (Exception ex)
                        {
                            
                            TempData["DeleteError"] = "Error deleting image file: " + ex.Message;
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        TempData["DeleteError"] = "Image file not found.";
                    }
                }
            }
            else
            {
                TempData["DeleteError"] = "Product not found.";
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/Cart/CartController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CartController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// <summary>
//   Defines the CartController.cs type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using SecureNetworks.DataBaseContext;
using SecureNetworks.Models.DBModels;
using SecureNetworks.Models.ViewModel;

namespace SecureNetworks.Controllers.Cart
{
    public class CartController : Controller
    {
        private readonly SecureNetworkDBContext _context;

        private readonly IHttpContextAccessor _httpContextAccessor;

        private readonly UserManager<ApplicationUserDBEntity> _userManager;

        private readonly SignInManager<ApplicationUserDBEntity> _signInManager;

        public CartController(SecureNetworkDBContext context, IHttpContextAccessor httpContextAccessor, UserManager<ApplicationUserDBEntity> userManager, SignInManager<ApplicationUserDBEntity> signInManager)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            TempData["CartItemCount"] = null;

            var cartItems = await GetCartItemsForCurrentUser();
            ViewBag.CartItemCount = await GetCartItemCount();

            // Set the cart item count in TempData
            int cartItemCount = await GetCartItemCount();
            TempData["CartItemCount"] = cartItemCount;

            return View(cartItems);
        }

        [HttpGet]
        public async Task<IActionResult> AddToCart(int id)
        {
            TempData["CartItemCount"] = null;

            // Retrieve product details from the database
            var product = await _context.tbl_SNProducts.FirstOrDefaultAsync(p => p.SNProductId == id);

            var checkIfUserSignedInOrNot = _signInManager.IsSignedIn(User);
            var user = _userManager.GetUserId(User);

            if (checkIfUserSignedInOrNot)
            {
                if (user != null)
                {
                    // Check if the item is already in the cart.
                    var getTheQuantity = await _context.tbl_SNUserCartEntities.FirstOrDefaultAsync(p => p.SNProductId == id);
                    if (getTheQuantity != null)
                    {
                        // If the item is already in the cart then increase the quantity.
                        getTheQuantity.SNProductQuantity += 1;

                        _context.Update(getTheQuantity);
                    }
                    else
                    {
                        // user has no cart but adding a new item to the existing cart.

                        if (product != null)
                        {
                            SNUserCartEntity newUserCartEntity = new SNUserCartEntity()
                            {
                                SNProductId = product.SNProductId,
                                SNUserId = user,
                                SNProductQuantity = 1,
                                SNProductPrice = product.SNProductPrice
                            };

                            await _context.tbl_SNUserCartEntities.AddAsync(newUserCartEntity);
                        }
                    }
                }
                else
                {
                    // user has no cart. Adding a brand new cart for the user.

                    if (product != null)
                    {
                        SNUserCartEntity newUserCartEntity = new SNUserCartEntity()
                        {
                            SNProductId = product.SNProductId,
                            SNUserId = user!,
                            SNProductQuantity = 1,
                            SNProductPrice = product.SNProductPrice
                        };

                        await _context.tbl_SNUserCartEntities.AddAsync(newUserCartEntity);
                    }
                    else
                    {
                        TempData["CartItemCount"] = $"No Products found for this user : {user} in the car";
                    }

                }

                await _context.SaveChangesAsync();
            }
            
            // Set the cart item count in TempData
            int cartItemCount = await GetCartItemCount();
            TempData["CartItemCount"] = cartItemCount;

            return RedirectToAction("Index", "SNProducts");
        }
        private async Task<int> GetCartItemCount()
        {
            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);
                if (user != null)
                {
                    return await _context.tbl_SNUserCartEntities
                        .Where(u => u.SNUserId == user.Id)
                        .SumAsync(u => u.SNProductQuantity);
                }
            }
            return 0;
        }
        private async Task<List<SNCartItemViewModel>> GetCartItemsForCurrentUser()
        {
            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);
                if (user != null)
                {
                    var cartItems = await (from uc in _context.tbl_SNUserCartEntities
                                           join p in _context.tbl_SNProducts on uc.SNProductId equals p.SNProductId
                                           where uc.SNUserId == user.Id
                                           select new SNCartItemViewModel
                                           {
                                               SNProductId = p.SNProductId,
                                               ImageUrl = p.SNProductImageUrl,
                                               SNProductName = p.SNProductName,
                                               SNProductPrice = p.SNProductPrice,
                                               SNProductQuantity = uc.SNProductQuantity
                                           }).ToListAsync();

                    return cartItems;
                }
            }
            return new List<SNCartItemViewModel>();
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int productId)
        {
            TempData["CartItemCount"] = "";

            // Retrieve the current user's ID from the HttpContext
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (userId == null)
            {
                // Handle the case where the user is not authenticated
                return Unauthorized();
            }

            // Find the item in the user's cart
            var cartItem = await _context.tbl_SNUserCartEntities.FirstOrDefaultAsync(c => c.SNProductId == productId && c.SNUserId == userId);

            if (cartItem != null)
            {
                _context.tbl_SNUserCartEntities.Remove(cartItem);
                await _context.SaveChangesAsync();

                // Return a success response
                return Json(new { success = true });
            }

            // Set the cart item count in TempData
            int cartItemCount = await GetCartItemCount();
            TempData["CartItemCount"] = cartItemCount;

            // Return an error response if the item was not found in the cart
            return Json(new { success = false });
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using SecureNetworks.Models.DBModels
@inject SignInManager<ApplicationUserDBEntity> SignInManager

@inject IHttpContextAccessor HttpContextAccessor

@{
    var isAdminUser = HttpContextAccessor.HttpContext!.Session.GetInt32("IsAdminUser");
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Secure Network</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Custom CSS -->
    <style>
        /* Ensure full-screen height */
        html, body {
            height: 100%;
        }

        /* Set carousel height */
        .carousel-item img {
            object-fit: cover;
            height: 80vh; /* Adjust as needed */
            width: 100%;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Secure Network</a>
                @if (SignInManager.IsSignedIn(User))
                {
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" style="color: black" asp-area="" asp-controller="SNProducts" asp-action="GetProductsByCategory" asp-route-category="NetworkDevices">NetworkDevices</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" style="color: black" asp-area="" asp-controller="SNProducts" asp-action="GetProductsByCategory" asp-route-category="TrainingCourses">TrainingCourses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" style="color: black" asp-area="" asp-controller="SNProducts" asp-action="GetProductsByCategory" asp-route-category="TestingTools">TestingTools</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" style="color: black" asp-area="" asp-controller="AboutUs" asp-action="Index">About</a>
                            </li>
                            @if (isAdminUser is 1)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" style="color: black" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                                </li>
                            }
                        </ul>
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item">
                                <a class="nav-link bi bi-cart" style="color: black" asp-area="" asp-controller="Cart" asp-action="Index">@TempData["CartItemCount"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link bi bi-person-circle" style="color: black" asp-area="" asp-controller="MyAccount" asp-action="MyAccount"></a>
                            </li>
                            <li class="nav-item">
                                <form id="logoutForm" asp-controller="User" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="nav-link btn btn-link" style="color: black">Logout</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" style="color: black" asp-controller="User" asp-action="SignIn">Login</a>
                        </li>
                    </ul>
                }
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Include other necessary scripts here -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>