Models/ViewModel/MyAccountViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SecureNetworks.Models.ViewModel
{
    public class MyAccountViewModel
    {
        [StringLength(100)]
        public string FirstName { get; set; }

        [StringLength(100)]
        public string LastName { get; set; }

        [StringLength(100)]
        public string Telephone { get; set; }

        [StringLength(100)]
        public string? Email { get; set; }

        [StringLength(100)]
        public string? PostCode { get; set; }
    }
}

Controllers/UserAccount/MyAccountController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="MyAccountController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// <summary>
//   Defines the MyAccountController.cs type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SecureNetworks.DataBaseContext;
using SecureNetworks.Models.DBModels;
using SecureNetworks.Models.ViewModel;

namespace SecureNetworks.Controllers.UserAccount
{
    public class MyAccountController : Controller
    {
        private readonly SecureNetworkDBContext _dbContext;

        private readonly UserManager<ApplicationUserDBEntity> _userManager;

        private readonly SignInManager<ApplicationUserDBEntity> _signInManager;

        public MyAccountController(SecureNetworkDBContext _dbContext, SignInManager<ApplicationUserDBEntity> signInManager, UserManager<ApplicationUserDBEntity> userManager)
        {
            this._dbContext = _dbContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }


        [HttpGet]
        public async Task<IActionResult> MyAccount()
        {
            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);

                if (user == null)
                {
                    return NotFound();
                }

                var model = new MyAccountViewModel
                {
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Telephone = user.Telephone,
                };

                return View(model);
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateAccount(MyAccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (_signInManager.IsSignedIn(User))
                {
                    var user = await _userManager.GetUserAsync(User);

                    if (user == null)
                    {
                        return NotFound();
                    }

                    // Retrieve user entity from the database based on the email
                    var userDetails = this._dbContext.AspNetUsers.FirstOrDefault(u => u.Email == user.Email);

                    if (userDetails != null)
                    {
                        // Update user properties with the values from the view model
                        userDetails.FirstName = model.FirstName;
                        userDetails.LastName = model.LastName;
                        userDetails.Telephone = model.Telephone;

                        // Update user in the database
                        var result = _dbContext.AspNetUsers.Update(userDetails);
                        await _dbContext.SaveChangesAsync();

                        // Update successful
                        return RedirectToAction("Index", "SNProducts");
                    }
                }

                // User not found
                ModelState.AddModelError(string.Empty, "User not found.");
            }

            // If ModelState is not valid, return the view with the model data and errors
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/MyAccount/MyAccount.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model SecureNetworks.Models.ViewModel.MyAccountViewModel

<h2 class="text-center mb-2" style="padding-top : 2em">My Account</h2>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow p-3 mb-5 bg-body rounded">
                <div class="card-body">
                    <form asp-action="UpdateAccount" asp-controller="MyAccount" method="post">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group mb-3">
                                    <label for="email" style="color: aliceblue">Email:</label>
                                    <input asp-for="Email" class="form-control" disabled readonly />
                                </div>
                                <div class="form-group mb-3">
                                    <label asp-for="FirstName" style="color: aliceblue">First Name:</label>
                                    <input asp-for="FirstName" class="form-control" />
                                </div>
                                <div class="form-group mb-3">
                                    <label asp-for="LastName" style="color: aliceblue">Last Name:</label>
                                    <input asp-for="LastName" class="form-control" />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group mb-3">
                                    <label asp-for="Telephone" style="color: aliceblue">Telephone:</label>
                                    <input asp-for="Telephone" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="mb-2">
                            <button type="submit" class="btn btn-primary mb-2">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>